version: '3.8'

services:
  authapi:
    build: ./AuthAPI
    container_name: authapi
    depends_on:
      - postgres
    ports:
      - "1111:1111"
    env_file:
      - AuthAPI/.env

  networkapi:
    build: ./NetworkAPI
    container_name: networkapi
    depends_on:
      - neo4j
    ports:
      - "2222:2222"
    env_file:
      - NetworkAPI/.env
    
  postapi:
    build: ./PostAPI
    container_name: postapi
    depends_on:
      - neo4j
    ports:
      - "3333:3333"
    env_file:
      - PostAPI/.env
  
  commentapi:
    build: ./CommentAPI
    container_name: commentapi
    depends_on:
      - neo4j
    ports:
      - "4444:4444"
    env_file:
      - CommentAPI/.env

  likesapi:
    build: ./LikesAPI
    container_name: likesapi
    depends_on:
      - neo4j
    ports:
      - "5555:5555"
    env_file:
      - CommentAPI/.env

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      
    ports:
      - "5432:5432"

  neo4j:
    image: neo4j
    container_name: neo4j
    environment:
      NEO4J_AUTH: none
      
    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - neo4j_data:/data/

## volumes to be generated, these are saved somewhere for repeated use by docker
volumes:
    neo4j_data:


      